# f2chat root BUILD file

load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = [
        "//lib/...",
        "//test/...",
    ],
    exclude_headers = "external",
    exclude_external_sources = True,
)
